AES Hiring Application/Wcf.AES.Jobs.Client/Controllers/ApplicantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;
using System.Web.Mvc;
using WcfAESJobs.Client.Models;
using WcfAESJobs.Client.ViewModels;
using WcfAESJobs.Client.WebService;

namespace WcfAESJobs.Client.Controllers
{
    public class ApplicantController : Controller
    {
        JobServiceClient js = new JobServiceClient();
     
        // GET: JobsPosting
        public ActionResult Index(string searchString, string selectedLocation)
        {
            OpenJobs[] All_Jobs = js.Get_Job_Posting_List();
            IEnumerable<OpenJobs> jobList = All_Jobs.ToList();

            var allUniqueLocations = jobList.Select(x => x.Job_Location).Distinct().ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                if (selectedLocation != "All Locations")
                {
                    jobList =
                        jobList.Where(
                            x => x.Job_Location.Contains(selectedLocation) && x.Job_Title.Contains(searchString));
                }
                if (selectedLocation == "All Locations")
                {
                    jobList = jobList.Where(x => x.Job_Title.Contains(searchString));
                }

                //jobList = jobList.Where(s => s.Job_Title.Contains(searchString)
                //                       || s.Job_Location.Contains(searchString));
            }
            else
            {
                if (selectedLocation == null)
                {
                    selectedLocation = "All Locations";
                }

                if (selectedLocation != "All Locations")
                {
                    jobList = jobList.Where(x => x.Job_Location.Contains(selectedLocation));
                }
            }

            JobPostingViewModel finalModel = new JobPostingViewModel { AllJobs = jobList, Locations = allUniqueLocations };

            return View(finalModel);
        }


        // GET: Applicant/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenJobs job = js.Get_Posting_By_ID(id);


            if (job == null)
            {
                return HttpNotFound();
            }

            var model = new OpenJobsModel
            {
                JobDescription = job.Job_Description,
                CloseDate = job.Close_Date,
                JobId = job.Job_ID,
                JobLocation = job.Job_Location,
                JobLocationCity = job.Job_Location_City,
                JobQualification = job.Job_Qualification,
                JobTitle = job.Job_Title,
                PostingId = job.Posting_ID
            };

            return View(model);
        }

        // GET: Applicant/Create
        [Authorize]
        public ActionResult Create(int? id)
        {
            ViewBag.Posting_ID = id;
            return View();
        }

        // POST: Applicant/Create
        [HttpPost]
        public ActionResult Create(int Posting_ID, ApplicantModel person)
        {
            try
            {
                
                /* applicant = new Applicant
                {
                    First_Name = person.First_Name,
                    Last_Name = person.Last_Name,
                    Address1 = person.Address1,
                    Address2 = person.Address2,
                    City = person.City,
                    State = person.State,
                    DOB = person.DOB,
                    Email = person.Email,
                    Phone = person.Phone

                };*/
                //int ApplicationID = js.Create_Application(applicant, Posting_ID);
                return RedirectToAction("Apply", "Application", new { id = 0 });
            }
            catch
            {
                return View();
            }
        }

        // GET: Applicant/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Applicant/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
            
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Applicant/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Applicant/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        public ActionResult ShowDetails(int id)
        {
            
            OpenJobs job = js.Get_Posting_By_ID(id);


            if (job == null)
            {
                return HttpNotFound();
            }

            var model = new OpenJobsModel
            {
                JobDescription = job.Job_Description,
                CloseDate = job.Close_Date,
                JobId = job.Job_ID,
                JobLocation = job.Job_Location,
                JobLocationCity = job.Job_Location_City,
                JobQualification = job.Job_Qualification,
                JobTitle = job.Job_Title,
                PostingId = job.Posting_ID
            };

            return this.PartialView("_Details", model);
        }

    }
}

AES Hiring Application/Wcf.AES.Jobs.Client/Controllers/JobsPostingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;
using System.Web.Mvc;
using WcfAESJobs.Client.WebService;
using WcfAESJobs.Client.ViewModels;
using WcfAESJobs.Client.Models;


namespace WcfAESJobs.Client.Controllers
{
    [Authorize(Roles="HiringSpecialist, SuperUser")]
    public class JobsPostingController : Controller
    {
        JobServiceClient js = new JobServiceClient();
     
        // GET: JobsPosting
        public ActionResult Index(string searchString,string selectedLocation)
        {
            OpenJobs[] All_Jobs = js.Get_Job_Posting_List();
            IEnumerable<OpenJobs> jobList = All_Jobs.ToList();

            var allUniqueLocations = jobList.Select(x => x.Job_Location).Distinct().ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                if (selectedLocation != "All Locations")
                {
                    jobList =
                        jobList.Where(
                            x => x.Job_Location.Contains(selectedLocation) && x.Job_Title.Contains(searchString));
                }
                if (selectedLocation == "All Locations")
                {
                    jobList = jobList.Where(x => x.Job_Title.Contains(searchString));
                }

                //jobList = jobList.Where(s => s.Job_Title.Contains(searchString)
                //                       || s.Job_Location.Contains(searchString));
            }
            else
            {
                if (selectedLocation == null)
                {
                    selectedLocation = "All Locations";
                }

                if (selectedLocation != "All Locations")
                {
                    jobList = jobList.Where(x => x.Job_Location.Contains(selectedLocation));
                }
            }

            JobPostingViewModel finalModel = new JobPostingViewModel {AllJobs = jobList , Locations = allUniqueLocations };
            
            return View(finalModel);
        }


        // GET: JobsPosting/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            OpenJobModel jobModel = new OpenJobModel();
            jobModel.Job = js.Get_Posting_By_ID(id);
            jobModel.ApplicationQuestions = js.getQuestionsByJobID(jobModel.Job.Job_ID).ToList();
            //OpenJobs job = js.Get_Posting_By_ID(id);
            if (jobModel == null)
            {
                return HttpNotFound();
            }
            return View(jobModel);
        }

        public ActionResult QuestionDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question[] question = js.getQuestionsByJobID(id);

            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }


        // GET: JobsPosting/Create
        public ActionResult Create()
        {
            ViewBag.Location_ID = new SelectList(js.Get_Store_Location_List(), "Location_ID", "Location_Name");
            ViewBag.Job_ID = new SelectList(js.Get_Job_Template_List(), "Job_ID", "Job_Title");
            ViewBag.Close_Date = new DateTime();
            return View();
        }


        // POST: JobsPosting/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "Location_ID, Job_ID, Close_Date")] NewPosting job)
        { 
            try
            {
                js.Create_Job_Posting(job);
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.Location_ID = new SelectList(js.Get_Store_Location_List(), "Location_ID", "Location_Name");
                ViewBag.Job_ID = new SelectList(js.Get_Job_Template_List(), "Job_ID", "Job_Title");
                ViewBag.Close_Date = new DateTime();
                return View(job);
            }
        }


        // GET: JobsPosting/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenJobs job = js.Get_Posting_By_ID(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }


        // POST: JobsPosting/Edit/5
        [HttpPost]
        public ActionResult Edit(OpenJobs job)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        // GET: JobsPosting/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenJobs job = js.Get_Posting_By_ID(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }


        // POST: JobsPosting/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                js.Delete_Job_Posting(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AES Hiring Application/Wcf.AES.Jobs.Client/Controllers/ScreeningController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WcfAESJobs.Client.WebService;

namespace WcfAESJobs.Client.Controllers
{
    [Authorize(Roles="Screener, SuperUser")]
    public class ScreeningController : Controller
    {
        // GET: Screening

        JobServiceClient js = new JobServiceClient();
        
        public ActionResult Index()
        {
            Job_Application[] applications = js.Get_Job_Application_List_By_Stage(1);

            return View(applications.ToList());
        }

        public ActionResult PhoneScreen()
        {
            Job_Application[] applications = js.Get_Job_Application_List_By_Stage(2);

            return View(applications.ToList());
        }

        public ActionResult Grade(int? id)
        {
            ViewBag.AppID = id;
            Question_Answer[] QA = js.Get_Answers_By_Application_ID(id);

            return View(QA.ToList());
        }

        public ActionResult SubmitGrade(string result, int App_ID)
        {

            if (result == "Pass")
            {
                js.Update_Application_Stage(App_ID, 2);
                ViewBag.StatusMessage = "Applicant Passed";
            }
            else if (result == "Fail")
            {
                js.Update_Application_Stage(App_ID, 0);
                ViewBag.StatusMessage = "Applicant Failed";
            }
            else
            {
                ViewBag.StatusMessage = "Request could not be processed";
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");

        }
    }
}

AES Hiring Application/Wcf.AES.Jobs.Client/Views/Shared/_Details.cshtml
@model WcfAESJobs.Client.Models.OpenJobsModel

@{
    ViewBag.Title = "Show Details";
}



<div class="col-sm-12" >
    <h2 style="color:cadetblue">@Model.JobTitle</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Job Title
        </dt>
       
        <dd>
            @Html.DisplayFor(model => model.JobTitle)<br /> <br />
        </dd>

        <dt>
            City
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobLocationCity)<br /> <br />
        </dd>
        <dt>
            Location
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobLocation)<br /> <br />
        </dd>
        <dt>
            Close Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CloseDate)<br /> <br />
        </dd>
        @*<dt>
                Job ID
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Job_ID)<br /> <br />
            </dd>

            <dt>
                Posting ID
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Posting_ID)<br /> <br />
            </dd>*@

        <dt>
            Description
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobDescription)<br /> <br />
        </dd>
        <dt>
            Qualifications
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobQualification)<br /> <br />
        </dd>



    </dl>
</div>
<div class="col-sm-12">
    @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |*@

    @Html.ActionLink("Apply", "Create", "Applicant", new {id = Model.PostingId}, new {@class = "btn btn-default"})&nbsp;
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>
<br/>

AES Hiring Application/Wcf.AES.Jobs.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>



<html>
<head>
    
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AES </title>
    @Styles.Render("~/Content/css")

    <link href="@Url.Content("~/Content/full-slider.css")" rel="stylesheet" type="text/css"/>


    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css"/>

    <script src="@Url.Content("~/Scripts/jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    @Scripts.Render("~/bundles/modernizr")

    <style>
        
       
         .colorWhite {
             color: white;
         }

        .navbar-inverse .navbar-nav > li > a {
            color: white;

        }

        .navbar-inverse:hover .navbar-nav > li > a:hover {
            color: gray;
            display: block;

        }
        .dropdown-menu li:hover .sub-menu {
            visibility: visible;
        }

        .dropdown:hover .dropdown-menu {
            display: block;
        }

        .navbar-inverse .navbar-brand {
            color: white;
        }

        .navbarBackgroundColor {
            background-color: #3b5998;
        }
    </style>

</head>
<body>
<div class="navbarBackgroundColor navbar navbar-inverse navbar-fixed-top ">
    <div class="container">
        <div class="navbar-header ">
            <button type="button" class="navbar-toggle " data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("AES Home", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse ">
            <ul class="nav navbar-nav ">
                @* <li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                <li>@Html.ActionLink("Job Postings", "Index", "Applicant")</li>
                @*<li>@Html.ActionLink("Index", "Index", "Home")</li>*@
                <li class="dropdown">
                    <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Admin Controls </a>
                    <ul class="dropdown-menu" role="menu">
                        <li>@Html.ActionLink("Job Postings", "Index", "JobsPosting")</li>
                        <li>@Html.ActionLink("Job Templates", "Index", "Job")</li>
                        <li>@Html.ActionLink("Questions", "Index", "Question")</li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Screening </a>
                    <ul class="dropdown-menu" role="menu">
                        <li>@Html.ActionLink("Screen Applications", "Index", "Screening")</li>
                        <li>@Html.ActionLink("Phone Interview", "PhoneScreen", "Screening")</li>
                    </ul>
                </li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
    @RenderSection("carousel", required: false)
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - AES Jobs by Barz </p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>